# Generated by Django 2.2.13 on 2020-08-05 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_star', models.IntegerField()),
                ('comment', models.CharField(max_length=500)),
            ],
        ),
    ]
